### ISSUE TITLE
Rename `fluid-type` mixin?

### ISSUE THREAD

**Issue by cmalven** [onedesign/one-sass-toolkit#14]
I'm not sure why I didn't notice this originally, but the `fluid-type` mixing we added awhile ago is probably over-prescriptive in what it is named, since it can essentially be used to make any property fluid (e.g. `padding`, `margin`, `line-height`, etc).

Should we rename it to just `fluid` to make it a little more clear how broadly it can be used? @brianjhanson?

**Comment by brianjhanson** [comment]
We're having some internal discussions about this set of tools as a whole in the next few weeks. So probably, but first I want to see if we can agree on a roadmap for these tools.
