### ISSUE TITLE
'$map' is undefined

### ISSUE THREAD

**Issue by purcebr** [onedesign/one-sass-toolkit#3]
Hey Guys - 

https://github.com/onedesign/one-sass-toolkit/blob/master/_color.scss#L79

Seeing an error here, seems like this should be `$color` in stead of `$map` ?

**Comment by cmalven** [comment]
Yep, I think your right @purcebr

This must've slipped through the cracks during https://github.com/onedesign/one-sass-toolkit/commit/091d123a72c0d9e94c10b4632ee47c92b8a1545a

**Comment by cmalven** [comment]
CC @brianjhanson

**Comment by purcebr** [comment]
Cool - added a pr - https://github.com/onedesign/one-sass-toolkit/pull/4/files
