### ISSUE TITLE
Need to add a font-smoothing mixin into this repo

### ISSUE THREAD

**Issue by molwells** [onedesign/one-sass-toolkit#8]
Without it, things blow up.

**Comment by cmalven** [comment]
Good call, I think we never noticed this before because we always had the font-smoothing mixin as a part of the project already.

**Comment by brianjhanson** [comment]
Yeah, took Molly and I awhile to debug why Four Loko was blowing up. Turned out to be because we were loading the utils in after this stuff. Hence 💣

**Comment by cmalven** [comment]
This should have been resolved by #9

@brianjhanson @molwells can either of you confirm this?
